name: Final Cron Job

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Download Chromedriver
      #   run: |
      #     wget -q https://storage.googleapis.com/chrome-for-testing-public/121.0.6167.184/linux64/chrome-headless-shell-linux64.zip
      #     unzip chrome-headless-shell-linux64.zip -d chromedriver
      #     chmod +x chromedriver
      #     sudo mv chromedriver /usr/local/bin/
      #     rm chrome-headless-shell-linux64.zip


      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      # - name: Set up Chrome environment
      #   run: echo "CHROME_BIN=/usr/bin/chromedriver" >> $GITHUB_ENV

      - name: Run WebDriverIO tests
        run: npx wdio run wdio.conf.js --headless
