name: WebDriverIO Cron Job

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Set up Chrome environment
        run: echo "CHROME_BIN=/usr/bin/google-chrome-stable" >> $GITHUB_ENV

      - name: Run WebDriverIO tests
        run: npx wdio run wdio.conf.js --headless
